// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class EnergyStarProduct
    {
        public EnergyStarProduct()
        {
            EnergyStarProductSpec = new HashSet<EnergyStarProductSpec>();
        }

        public int IdPdt { get; set; }
        public int IPdtCorporationId { get; set; }
        public int? VrPdtCode { get; set; }
        public string VrPdtName { get; set; }
        public string VrPdtEngName { get; set; }
        public string VrPdtUse { get; set; }
        public string VrPdtEngUse { get; set; }
        public string VrPdtDesc { get; set; }
        public string VrPdtEngDesc { get; set; }
        public int IPdtCriteriaId { get; set; }
        public string VrPdtSmallpicUrl { get; set; }
        public string VrPdtPicUrl { get; set; }
        public DateTime DtPdtCreate { get; set; }
        public DateTime DtPdtModify { get; set; }
        public int IdContacts { get; set; }

        public virtual EnergyStarCorporation IPdtCorporation { get; set; }
        public virtual EnergyStarCriteria IPdtCriteria { get; set; }
        public virtual EnergyStarContact IdContactsNavigation { get; set; }
        public virtual ICollection<EnergyStarProductSpec> EnergyStarProductSpec { get; set; }
    }
}