// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class EnergyStarContact
    {
        public EnergyStarContact()
        {
            EnergyStarProduct = new HashSet<EnergyStarProduct>();
        }

        public int IdContacts { get; set; }
        public string VrContacts { get; set; }
        public string VrContactsPhone { get; set; }
        public string VrContactsEmail { get; set; }
        public string VrContactsFax { get; set; }
        public string VrContactsAddress { get; set; }
        public DateTime DtCreate { get; set; }
        public DateTime DtModify { get; set; }

        public virtual ICollection<EnergyStarProduct> EnergyStarProduct { get; set; }
    }
}