// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class EnergyStarCorporation
    {
        public EnergyStarCorporation()
        {
            EnergyStarProduct = new HashSet<EnergyStarProduct>();
        }

        public int IdCop { get; set; }
        public int? VrCopCode { get; set; }
        public string VrCopName { get; set; }
        public string VrCopEngName { get; set; }
        public string VrCopPrincipal { get; set; }
        public string VrCopPrincipalPhone { get; set; }
        public string VrCopPrincipalEmail { get; set; }
        public string VrCopPrincipalFax { get; set; }
        public string VrCopUrl { get; set; }
        public DateTime DtCopCreate { get; set; }
        public DateTime DtCopModify { get; set; }

        public virtual ICollection<EnergyStarProduct> EnergyStarProduct { get; set; }
    }
}