// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class EnergyStarProductSpec
    {
        public int IdPds { get; set; }
        public int IPdsProductId { get; set; }
        public int IPdsSeqNum { get; set; }
        public string VrPdsName { get; set; }
        public string VrPdsEngName { get; set; }
        public string VrPdsDesc { get; set; }
        public string VrPdsEngDesc { get; set; }
        public DateTime DtPdsCreate { get; set; }
        public DateTime DtPdsModify { get; set; }

        public virtual EnergyStarProduct IPdsProduct { get; set; }
    }
}