// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class EnergyStarCriteria
    {
        public EnergyStarCriteria()
        {
            EnergyStarProduct = new HashSet<EnergyStarProduct>();
        }

        public int IdCrt { get; set; }
        public int ICrtLabelTypeId { get; set; }
        public string VrCrtCode { get; set; }
        public string VrCrtName { get; set; }
        public string VrCrtEngName { get; set; }
        public string VrCrtDesc { get; set; }
        public string VrCrtEngDesc { get; set; }
        public DateTime DtCrtCreate { get; set; }
        public DateTime DtCrtModify { get; set; }
        public string VrCrtShowName { get; set; }
        public string VrCrtShowEngName { get; set; }

        public virtual ICollection<EnergyStarProduct> EnergyStarProduct { get; set; }
    }
}