// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class HomeMedia
    {
        public int Id { get; set; }
        public string CartoonBanner { get; set; }
        public string MediaBanner { get; set; }
        public string SecondBanner { get; set; }
        public string CartoonAccessibilityTips { get; set; }
        public string MediaAccessibilityTips { get; set; }
        public string SecondAccessibilityTips { get; set; }
        public DateTime BeginDate { get; set; }
        public DateTime OffDate { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastModifyUser { get; set; }
        public DateTime? LastModifyDate { get; set; }
        public string FirstModifyUser { get; set; }
        public DateTime? FirstModifyDate { get; set; }
        public string SecondModifyUser { get; set; }
        public DateTime? SecondModifyDate { get; set; }
        public string ThirdModifyUser { get; set; }
        public DateTime? ThirdModifyDate { get; set; }
    }
}