// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class InfoTag
    {
        public int Id { get; set; }
        public int InfoId { get; set; }
        public int TagId { get; set; }
        public byte? TagType { get; set; }

        public virtual Infos Info { get; set; }
        public virtual Tag Tag { get; set; }
    }
}