// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class Infos
    {
        public Infos()
        {
            InfoTag = new HashSet<InfoTag>();
        }

        public int Id { get; set; }
        public string HtmlUrl { get; set; }
        public string Title { get; set; }
        public short? Dtype { get; set; }
        public string HtmlContent { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public DateTime? PublishDate { get; set; }
        public DateTime? OffDateTime { get; set; }

        public virtual ICollection<InfoTag> InfoTag { get; set; }
    }
}