// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class Knowledged
    {
        public int Id { get; set; }
        public string CostYear { get; set; }
        public string PlanName { get; set; }
        public string NumberLaw { get; set; }
        public string DefiProjectClass { get; set; }
        public string ExecutiveUnit { get; set; }
        public string PlanHost { get; set; }
        public string ProjectClass { get; set; }
        public string KeywordTw { get; set; }
        public string KeywordEng { get; set; }
        public string SummaryTw { get; set; }
        public string InfoLink { get; set; }
    }
}