// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCISWebCore.Models.EF
{
    public partial class Tag
    {
        public Tag()
        {
            InfoTag = new HashSet<InfoTag>();
        }

        public int Id { get; set; }
        public string TagName { get; set; }

        public virtual ICollection<InfoTag> InfoTag { get; set; }
    }
}